---

  - name: 1.2.1 Ensure package manager repositories are configured (Not Scored)
    lineinfile:
      dest: /etc/apt/sources.list
      line: '{{item}}'
      state: present
      create: yes
    with_items:
      - 'deb http://archive.ubuntu.com/ubuntu/ bionic main restricted'
      - 'deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted'
      - 'deb http://archive.ubuntu.com/ubuntu/ bionic universe'
      - 'deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe'
      - 'deb http://archive.ubuntu.com/ubuntu/ bionic multiverse'
      - 'deb http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse'
      - 'deb http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse'
      - 'deb http://security.ubuntu.com/ubuntu bionic-security main restricted'
      - 'deb http://security.ubuntu.com/ubuntu bionic-security universe'
      - 'deb http://security.ubuntu.com/ubuntu bionic-security multiverse'
    tags:
      - section1
      - section1.2
      - section1.2.1
      - server_level_1
      - workstation_level_1

  - name: 1.2.2 Ensure GPG keys are configured (Not Scored)
    lineinfile:
      dest: /etc/apt/apt.conf.d/99GPG-apt
      line: 'APT::Get::AllowUnauthenticated "false";'
      state: present
      create: yes
    tags:
      - section1
      - section1.2
      - section1.2.2
      - server_level_1
      - workstation_level_1
